### Verified
GET http://localhost:8000/verified/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZjU5ZDc3NTgwMTU3N2Q1OWU5MjM2OCIsImlhdCI6MTY2MDI2NDYwM30.FPUD3OcNA_WlDEnx7ZQpse_PRKIAX-t0V3jE8vTSTRc

###
POST http://localhost:8000/verified/
Content-Type: application/json

{
    "title": "Verified"
}

### Register
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "username":"Tony",
    "email":"tony@gmail.com",
    "password": "tony"
}

### Login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "tony@gmail.com",
    "password": "tony"
}

### User
GET http://localhost:8000/users/62f59d775801577d59e92368/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZjU5ZDc3NTgwMTU3N2Q1OWU5MjM2OCIsImlhdCI6MTY2MDI2NDYwM30.FPUD3OcNA_WlDEnx7ZQpse_PRKIAX-t0V3jE8vTSTRc

### 
GET http://localhost:8000/users

###
PUT http://localhost:8000/users/62eb3008bd9265a376a1528f
Content-Type: application/json

{
    "username": "Ivan Kristiawan",
    "password": "ivanteens",
    "isAdmin": false
}

###
DELETE http://localhost:8000/users/62e906d808f0aee922bc7e5d